apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-bitbucketserver
spec:
  crossplane:
    version: ">=v1.0.0"
  controller:
    image: tomasmota/provider-bitbucketserver:v0.14.0
    permissionRequests:
    - apiGroups:
      - apiextensions.crossplane.io
      resources:
      - compositions
      verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch