# Setting up a provider in a cluster with crossplane installed can be done in this way
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-bitbucketserver
spec:
  package: registry.hub.docker.com/tomasmota/provider-bitbucketserver-amd64:v0.0.0-33.gd2ef069
  controllerConfigRef:
    name: debug-config