apiVersion: project.bitbucketserver.crossplane.io/v1alpha1
kind: Project
metadata:
  name: testproject
spec:
  forProvider:
    name: providertest
    key: PVT
  providerConfigRef:
    name: mybitbucketserver